//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRepair.DBStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public System.DateTime date_added { get; set; }
        public string equipment { get; set; }
        public int fault_type { get; set; }
        public string problem_description { get; set; }
        public string client_fullname { get; set; }
        public string client_phoneNumber { get; set; }
        public int status_id { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> executor_id { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string materials { get; set; }
        public Nullable<decimal> price { get; set; }
        public string fault_reason { get; set; }
        public string provided_help { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Fault Fault { get; set; }
        public virtual Status Status { get; set; }
    }
}
